# Generated by Django 5.1.3 on 2025-02-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tijo_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='b_img',
        ),
        migrations.AddField(
            model_name='banner',
            name='B_img',
            field=models.ImageField(blank=True, null=True, upload_to='Banner'),
        ),
    ]
