# Generated by Django 5.1.6 on 2025-02-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tijo_portfolio', '0002_remove_banner_b_img_banner_b_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, max_length=30, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('P_num', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('degree', models.CharField(blank=True, max_length=10, null=True)),
                ('web', models.CharField(blank=True, max_length=10, null=True)),
                ('p_img', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
    ]
