# Generated by Django 5.1.6 on 2025-02-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tijo_portfolio', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Age',
        ),
        migrations.AddField(
            model_name='profile',
            name='Dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
