# Generated by Django 5.1.6 on 2025-02-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tijo_portfolio', '0005_alter_profile_city_alter_profile_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='web',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
