# Generated by Django 5.1.6 on 2025-02-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tijo_portfolio', '0007_profile_about_profile_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(blank=True, max_length=30, null=True)),
                ('s_value', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
