# Generated by Django 5.1.6 on 2025-02-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tijo_portfolio', '0009_frontndskills_rename_skills_backendskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(blank=True, max_length=50, null=True)),
                ('collegename', models.CharField(blank=True, max_length=50, null=True)),
                ('s_year', models.DateField(blank=True, null=True)),
                ('e_year', models.DateField(blank=True, null=True)),
                ('Company', models.CharField(blank=True, max_length=60, null=True)),
                ('cs_year', models.DateField(blank=True, null=True)),
                ('ce_year', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
