# Generated by Django 5.1.6 on 2025-02-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tijo_portfolio', '0010_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='experence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(blank=True, max_length=60, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('discriptions', models.CharField(blank=True, max_length=1000, null=True)),
                ('cs_year', models.DateField(blank=True, null=True)),
                ('ce_year', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='ce_year',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='cs_year',
        ),
    ]
