# Generated by Django 5.1.6 on 2025-02-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tijo_portfolio', '0011_experence_remove_resume_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, max_length=20, null=True)),
                ('p_dis', models.CharField(blank=True, max_length=100, null=True)),
                ('p_img', models.ImageField(blank=True, null=True, upload_to='projects')),
            ],
        ),
    ]
