# Generated by Django 5.1.6 on 2025-02-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tijo_portfolio', '0012_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='p_dis',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
