# Generated by Django 5.1.6 on 2025-02-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tijo_portfolio', '0014_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fcbk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='insta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
