# Generated by Django 5.1.6 on 2025-02-24 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tijo_portfolio', '0016_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='video',
            new_name='Project_video',
        ),
    ]
